### ISSUE TITLE
Generate Float syntax for Kotlin

### ISSUE THREAD

**Issue by BryanJBryce** [jeffdcamp/dbtools-android#8]
Currently if you define a Float in the schema with a default value

`<field name="percent" jdbcDataType="FLOAT" defaultValue="0.5"/>`

when the the BaseRecord is generated the default value lacks the `F` or `f` endfix to make the value a float in Kotlin. The errors says: "The floating-point literal does not conform to the expected type Float"

`open var percent: Float = 0.5` should be generated `open var percent: Float = 0.5F`

**Comment by BryanJBryce** [comment]
Never mind, it requires a lower case 'f' :)

**Comment by BryanJBryce** [comment]
Actually, you get a runtime crash with the 'f' in the XML.

**Comment by jeffdcamp** [comment]
The "defaultValue" of the schema.xml is designed to set the default value to exactly what you put in that field.  So you should add the "f" to the default value:

    <field name="percent" jdbcDataType="FLOAT" defaultValue="0.5f"/>

This allows you to also do things like:

    <field name="percent" jdbcDataType="FLOAT" defaultValue="com.company.app.AppDefaults.DEFAULT_PERCENT"/>

Which then would produce:

open var percent: Float = com.company.app.AppDefaults.DEFAULT_PERCENT
